
# Ruff settings: https://docs.astral.sh/ruff/editors/setup/#helix

[[language]]
name = "python"
rulers = [ 88, ]
language-servers = ["pylsp", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "markdown"
text-width = 100
soft-wrap.wrap-at-text-width = true
